DATA_NATURAL:
  data_name: FLARE
  num_classes: 5

RUN:
  seed: 1
  batch_size: 1

CLASSIFIER:
  classifier_dir: '/scratch/fgranese/Mead-detector/checkpoints/classifiers/' # directory containing the classifier model
  loss: 'g_upper' # loss used to fool the model
  model_type: 'margin'

ADV_CREATION:
  train: False
  epsilon:  0.00035
  T: 1.0
  norm: 'np.inf'  # 1, 2, 'inf', np.inf
  strategy: 'fgsm' # pgd, fgsm, bim, sa, cwi
  adv_file_path: '/scratch/fgranese/data_projects/FARAD/detectors/adv_data/'

