TRAIN:
  switch: False
  PGDi:
    epsilon: 0.125 # 0.03125, 0.0625, 0.125, 0.25, 0.3125, 0.5
    perturb_steps: 5
#    loss_train: 'Rao' # loss to use to train the detector

TEST:
  thrs_size: 200
  ATTACK:
    data_dir: /scratch/fgranese/data_projects/FARAD/detectors/adv_data/ # contains the adversarial data
    epsilon_test: 0.03125 # check Tab.1
    norm: 'inf' # 1, 2, 'inf', 'none'
    aa: False
  RESULTS:
    res_dir: results/salad/ # contains the results of the evaluation

DATA_NATURAL:
  data_name: cifar10

DETECTOR:
  DETECTOR_MODEL: # To change the structure of the detector
    layers: 3
    nodes: 256
    save_freq: 1
  batch_size: 500
  epochs_detector: 100
  resume_train_detector: False
  resume_epoch: 100 # checkpoint to load at testing time or epoch to resume training
  lr: 0.01
  weight_decay: 0.0005
  momentum: 0.
  seed: 1
  classifier_dir: checkpoints/classifiers/ # directory containing the classifier model
  detector_dir: /scratch/fgranese/Mead-detector/checkpoints/detectors/ # directory containing the detector model
  nesterov: False
  device: 0

