DATA_NATURAL:
  data_name: cifar100
  num_classes: 100

RUN:
  seed: 1
  batch_size: 1000

CLASSIFIER:
  classifier_dir: '/scratch/fgranese/Mead-detector/checkpoints/classifiers/' # directory containing the classifier model
  loss: 'CE' # loss used to fool the model

ADV_CREATION:
  epsilon: 70
  norm: 1 # 1, 2, 'inf', np.inf
  strategy: 'pgd' # pgd, fgsm, bim, sa, cwi
  adv_file_path: '/scratch/fgranese/data_projects/FARAD/detectors/adv_data/'

