DATA_NATURAL:
  data_name: cifar10
  num_classes: 100

RUN:
  seed: 1
  batch_size: 500

CLASSIFIER:
  classifier_dir: '/scratch/fgranese/Mead-detector/checkpoints/classifiers/' # directory containing the classifier model
  loss: 'CE' # loss used to fool the model

DETECTOR:
  detector_dir: '/scratch/fgranese/detectors_review/results/nss/cifar100/CE_pgdi_0.03125/'
  loss_adv: null # loss used to attack the detector

ADV_CREATION:
  strategy: 'sa'
  adv_file_path: '/scratch/fgranese/data_projects/FARAD/detectors/adv_data/'
  alpha: #[1e-3 1e-2 1e-1 1 1e1 1e2 1e3]
    - 1e3
